In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.DataFrame({
    'date': [
        '2019-12-10',
        '15/08/2018',
        'October 23, 2018',
        'invalid',
        None
    ],
    'product_id': [5628, 3646, 1859, 7292, 4344],
    'city_id': [25, 14, 25, 25, 25],
    'orders': [3, 157, 1, 1, 3]
})

In [3]:
date.head()

               date  product_id  city_id  orders
0        2019-12-10        5628       25       3
1        15/08/2018        3646       14     157
2  October 23, 2018        1859       25       1
3           invalid        7292       25       1
4               NaN        4344       25       3

In [4]:
time = pd.DataFrame({
    'date': [
        '2013-12-15 00:50:00',
        '2014-04-29 23:40:00',
        '2012-12-30 00:21:00',
        '2014-11-28 00:31:00',
        '2013-10-26 23:11:00'
    ],
    'msg': [
        'hello',
        'good morning',
        'call me',
        'meeting at 5',
        'see you tomorrow'
    ]
})

time.head()

                  date               msg
0  2013-12-15 00:50:00             hello
1  2014-04-29 23:40:00      good morning
2  2012-12-30 00:21:00           call me
3  2014-11-28 00:31:00      meeting at 5
4  2013-10-26 23:11:00  see you tomorrow

In [5]:

time.head()

                  date               msg
0  2013-12-15 00:50:00             hello
1  2014-04-29 23:40:00      good morning
2  2012-12-30 00:21:00           call me
3  2014-11-28 00:31:00      meeting at 5
4  2013-10-26 23:11:00  see you tomorrow

In [6]:
date.info()
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        4 non-null      str
 1   product_id  5 non-null      int64
 2   city_id     5 non-null      int64
 3   orders      5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 292.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    5 non-null      str
 1   msg     5 non-null      str
dtypes: str(2)
memory usage: 212.0 bytes

In [7]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

ValueError: time data "15/08/2018" doesn't match format "%Y-%m-%d". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [8]:
date.head()

               date  product_id  city_id  orders
0        2019-12-10        5628       25       3
1        15/08/2018        3646       14     157
2  October 23, 2018        1859       25       1
3           invalid        7292       25       1
4               NaN        4344       25       3

In [9]:
date['date'] = pd.to_datetime(
    date['date'],
    format='mixed',
    errors='coerce'
)

In [10]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3        NaT        7292       25       1
4        NaT        4344       25       3

In [12]:
date['year']= date['date'].dt.year.astype('Int64')

date.sample(5)

        date  product_id  city_id  orders  year
4        NaT        4344       25       3  <NA>
2 2018-10-23        1859       25       1  2018
0 2019-12-10        5628       25       3  2019
3        NaT        7292       25       1  <NA>
1 2018-08-15        3646       14     157  2018

In [25]:
# month name
date['date_month_name'] = date['date'].dt.month_name()

# month number
date['date_month_no'] = date['date'].dt.month

# day
date['date_day'] = date['date'].dt.day

# day of week
date['date_dow'] = date['date'].dt.dayofweek

# day name
date['date_dow_name'] = date['date'].dt.day_name()

# weekend
date['date_is_weekend'] = np.where(
    date['date_dow_name'].isin(['Sunday', 'Saturday']),
    1,
    0
)

# week number
date['date_week'] = date['date'].dt.isocalendar().week

# quarter
date['quarter'] = date['date'].dt.quarter

# semester
date['semester'] = np.where(
    date['quarter'].isin([1, 2]),
    1,
    2
)

In [14]:
# Extract Time elapsed between dates
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 9, 19, 0, 49, 55, 973754)

In [15]:
today - date['date']

0   2475 days 00:49:55.973754
1   2957 days 00:49:55.973754
2   2888 days 00:49:55.973754
3                         NaT
4                         NaT
Name: date, dtype: timedelta64[us]

In [26]:
(today - date['date']).dt.days
# Days passed
date['days_passed'] = (today - date['date']).dt.days

# Months passed (approx.)
date['months_passed'] = np.round(
    date['days_passed'] / 30,
    0
)

In [18]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    5 non-null      str
 1   msg     5 non-null      str
dtypes: str(2)
memory usage: 212.0 bytes

In [19]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [20]:

time.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    5 non-null      datetime64[us]
 1   msg     5 non-null      str
dtypes: datetime64[us](1), str(1)
memory usage: 212.0 bytes

In [21]:

time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

                 date               msg  hour  min  sec
0 2013-12-15 00:50:00             hello     0   50    0
1 2014-04-29 23:40:00      good morning    23   40    0
2 2012-12-30 00:21:00           call me     0   21    0
3 2014-11-28 00:31:00      meeting at 5     0   31    0
4 2013-10-26 23:11:00  see you tomorrow    23   11    0

In [22]:
time['time'] = time['date'].dt.time

time.head()

                 date               msg  hour  min  sec      time
0 2013-12-15 00:50:00             hello     0   50    0  00:50:00
1 2014-04-29 23:40:00      good morning    23   40    0  23:40:00
2 2012-12-30 00:21:00           call me     0   21    0  00:21:00
3 2014-11-28 00:31:00      meeting at 5     0   31    0  00:31:00
4 2013-10-26 23:11:00  see you tomorrow    23   11    0  23:11:00

In [23]:
today - time['date']

0   4660 days 23:59:55.973754
1   4525 days 01:09:55.973754
2   5011 days 00:28:55.973754
3   4313 days 00:18:55.973754
4   4710 days 01:38:55.973754
Name: date, dtype: timedelta64[us]

In [24]:

# in seconds

(today - time['date'])/np.timedelta64(1,'s')
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

# in hours

(today - time['date'])/np.timedelta64(1,'h')

0    111863.998882
1    108601.165548
2    120264.482215
3    103512.315548
4    113041.648882
Name: date, dtype: float64