In [1]:
#without piplelines
import numpy as np 
import pandas as pd 
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MinMaxScaler
tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
tips.drop(columns=['size'],inplace=True)
tips.head()

   total_bill   tip     sex smoker  day    time
0       16.99  1.01  Female     No  Sun  Dinner
1       10.34  1.66    Male     No  Sun  Dinner
2       21.01  3.50    Male     No  Sun  Dinner
3       23.68  3.31    Male     No  Sun  Dinner
4       24.59  3.61  Female     No  Sun  Dinner

In [3]:
y=tips['tip']
x= tips.drop(columns=['tip'],inplace=True)

x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)

TypeError: Expected sequence or array-like, got <class 'NoneType'>